ControlFocus("Open","","Edit1")
Sleep (2000)
ControlSetText("Open","","Edit1","C:\Users\Lenovo\Downloads\Amruta Resume (3).docx")
Sleep(2000)
ControlFocus("Open","","Button1")
ControlFocus("Open","","Button1")
